### PR TITLE
Added all four versions of my Gotham Sass logo in svg format to /assets/...

### PR DESCRIPTION
**Pull request by Loosetony**
...WIP

### CODE REVIEW

**Comment by misscs** [comment]
@Loosetony by WIP do you mean more assets to come? 

Also, thanks so much for submitting!

**Comment by adekunleoduye** [comment]
@misscs WIP is a folder I created a couple of weeks back...@Loosetony just put the 4 svgs in there.

Thanks again!

**Comment by Loosetony** [comment]
You're welcome! And feel free to change the colors to whatever suits you.
Not sure if there's a place for attribution for designing the logo, but if so I'd appreciate the note. ...............................................
Anthony Cangelosi 
loosetony@yahoo.com
...............................................

 

     On Thursday, January 29, 2015 12:50 PM, Adekunle Oduye <notifications@github.com> wrote:
   

 @misscs WIP is a folder I created a couple of weeks back...@Loosetony just put the 4 svgs in there.Thanks again!—

**Comment by misscs** [comment]
@Loosetony you'll definitely be attributed on site!

**Pull request merged**
